version: '3.9'
services:
    nginx:
        restart: always
        build: 
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports:
            - '3050:80'
        depends_on: 
            - api
            - client
    client:
        stdin_open: true
        build: 
            dockerfile: Dockerfile.dev
            context: ./client
        volumes:
            - /app/node_modules
            - ./client:/app 
    api:
        build:
            dockerfile: Dockerfile.dev
            context: ./server
        volumes: 
            - /app/node_modules
            - ./server:/app
        environment:
            - ME_CONFIG_MONGODB_PORT=27017
            - MONGO_INITDB_DATABASE=vehicle
            - SECRET=PasteYourSecretEnvVarHere
            - HOST=mongo
        depends_on: 
            - mongo
        ports:
            - '3000:3000'    
    mongo:
        image: mongo
        environment:
            - ME_CONFIG_MONGODB_PORT=27017
            - MONGO_INITDB_DATABASE=vehicle
        ports:
            - '27017:27017'